base_local_planner: dwa_local_planner/DWAPlannerROS
DWAPlannerROS:
  holonomic_robot: true
# Robot Configuration Parameters
  max_vel_x: 0.22
  min_vel_x: -0.22

  max_vel_y: 0
  min_vel_y: 0

# The velocity when robot is moving in acd  straight line
  max_vel_trans:  0.22
  min_vel_trans:  0.11

  max_vel_theta: 2.75
  min_vel_theta: -2.75

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2 

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.5
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.5
  sim_granularity: 0.02 
  vx_samples: 15
  vy_samples: 15
  vth_samples: 20
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.5
  forward_point_distance: 0.8
  stop_time_buffer: 0.5
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
